app/controllers/admin_controller.rb
app/controllers/ajax_controller.rb
app/controllers/application_controller.rb
app/controllers/logs_controller.rb
app/controllers/pages_controller.rb
app/controllers/statuses_controller.rb
app/controllers/users_controller.rb
app/views/admin/statuses.html.erb
app/views/layouts/application.html.erb
app/views/layouts/error.html.erb
app/views/pages/for_users_smart_phone.html.erb
app/views/pages/sorry.html.erb
app/views/shared/_footer_smart_phone.html.erb
app/views/shared/_to_page_top.html.erb
app/views/shared/_to_page_top_smart_phone.html.erb
app/views/statuses/import.html.erb
app/views/statuses/import_smart_phone.html.erb
app/views/users/home_timeline.html.erb
app/views/users/home_timeline_smart_phone.html.erb
app/views/users/index.html.erb
app/views/users/index_smart_phone.html.erb
app/views/users/public_timeline.html.erb
app/views/users/public_timeline_smart_phone.html.erb
app/views/users/sent_tweets.html.erb
app/views/users/sent_tweets_smart_phone.html.erb
app/views/users/setting.html.erb
app/views/users/setting_smart_phone.html.erb
config/routes.rb

Remove all the codes like `@show_foo_flag = false` from controllers, to make controllers thin.
Use `content_for` in the `view` instead.

Remove show flags

---

config/database.sample.yml
config/database.travis.yml
db/schema.rb

- Apply `utf8mb4` as charset
- Apply `utf8mb4_bin` as collation

handle with emojis

---

Gemfile
Gemfile.lock
spec/factories/friends.rb
spec/factories/statuses.rb
spec/factories/users.rb
spec/models/user_spec.rb

https://github.com/thoughtbot/factory_bot/blob/master/NAME.md

Factory girl to factory bot

---

app/controllers/ajax_controller.rb

```ruby
NoMethodError (undefined method `pop' for #<Status::ActiveRecord_Relation...
```
https://github.com/rails/rails/pull/13314/files#diff-563ce9140aa399b5ba97bb2a64b7c568R43

Upgrate Rails to 4.1

---

app/controllers/session_controller.rb
app/jobs/tweet_import_job.rb
app/models/user.rb
app/views/shared/_global_header.html.erb
app/views/shared/_global_header_smart_phone.html.erb
db/migrate/20180513054318_change_column_initialized_flag_to_finished_initial_import_on_users.rb
db/schema.rb
spec/factories/users.rb
spec/models/user_spec.rb

- Change column name #initialized_flag with #finished_initial_import
- Replace those logics using User#initialized_flag / User#has_impored? with User#finished_initial_import
- Insert new logic for updating User#finished_initial_import to the end point of  tweet import.

Abandon iniitialized flag

---

.circleci/config.yml
Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/production.rb

closes https://github.com/tbotaq/jump_pm/issues/31

Issue#31/deploy on merged

---

app/controllers/users_controller.rb
config/routes.rb

closes https://github.com/tbotaq/jump_pm/issues/32

Revert "implement action to check if sentry works"

---

app/models/status.rb
app/models/tweeted_date/public.rb

closes https://github.com/tbotaq/jump_pm/issues/48

Issue#48/correct timezone in view

---

app/models/status.rb
app/models/tweeted_date/public.rb

Reverts tbotaq/jump#91
needs appropriate indexing before applying this change

Revert "Issue#48/correct timezone in view"

---

app/models/status.rb

closes https://github.com/tbotaq/jump_pm/issues/48
closes https://github.com/tbotaq/jump/pull/93

issue#48/correct_timezone_in_term_selector

---

app/models/status.rb
app/models/timeline/home_timeline.rb
app/models/timeline/public_timeline.rb
app/models/timeline/user_timeline.rb
spec/factories/statuses.rb
spec/models/status_spec.rb
spec/rails_helper.rb

closes https://github.com/tbotaq/jump_pm/issues/54

Issue#54/refactor Status.get_status_in_date

---

app/models/status.rb
spec/models/status_spec.rb

closes https://github.com/tbotaq/jump-pm/issues/396

Fix incorrect validation on rt_text 

---

app/models/status.rb
db/migrate/20191113140607_change_type_of_text_to_text_on_statuses.rb
db/migrate/20191113143100_change_type_of_rt_text_to_text_on_statuses.rb
db/schema.rb
spec/models/status_spec.rb

closes https://github.com/tbotaq/jump-pm/issues/397

Tweak the limit of the length of tweet's text to be large enough

---

app/models/user.rb
spec/models/user_spec.rb
spec/requests/users/get_spec.rb

closes https://github.com/tbotaq/jump-pm/issues/395

Hide protected users on top.

---

app/controllers/stats_controller.rb
frontend/src/components/Top.jsx
spec/requests/stats_spec.rb

closes https://github.com/tbotaq/jump-pm/issues/400

Issue#400/show user count on top

---

frontend/package.json
frontend/src/react-app-env.d.ts
frontend/tsconfig.json
frontend/yarn.lock

closes https://github.com/tbotaq/jump-pm/issues/401

Issue#401/prepare ts env

---

app/controllers/stats_controller.rb
app/models/status.rb
app/models/tweet_import_progress.rb
app/models/user.rb
frontend/.eslintrc.json
frontend/src/components/DataManagement.tsx
frontend/src/components/Import.tsx
frontend/src/components/Top.tsx
frontend/src/components/TweetCard.tsx
frontend/src/components/TweetList.tsx
frontend/src/components/UserProfile.tsx
frontend/src/components/head_nav/UserMenu.tsx
frontend/src/models/tweet.ts
frontend/src/models/user.ts
frontend/src/utils/api/types.ts
frontend/src/utils/linkifyTweetText.ts
spec/models/status_spec.rb
spec/models/tweet_import_progress_spec.rb
spec/models/user_spec.rb
spec/requests/stats_spec.rb
spec/requests/statuses_spec.rb
spec/requests/users/followees/statuses_spec.rb
spec/requests/users/get_spec.rb
spec/requests/users/statuses/get_spec.rb
spec/requests/users/tweet_import_progresses_spec.rb

closes https://github.com/tbotaq/jump-pm/issues/408

Camelize identifiers in TS

---

.github/workflows/frontend.yml

closes https://github.com/tbotaq/jump-pm/issues/414

Run build workflow with the real command

---

deploy/config/deploy.rb

closes https://github.com/tbotaq/jump-pm/issues/415

Tweak the number of kept releases to 5

---

spec/requests/statuses_spec.rb
spec/requests/users/followees/statuses_spec.rb
spec/requests/users/statuses/get_spec.rb
spec/services/collect_followee_statuses_service_spec.rb
spec/services/collect_public_statuses_service_spec.rb
spec/services/collect_user_statuses_service_spec.rb

closes https://github.com/tbotaq/jump-pm/issues/398

chore: Remove useless assignments

---

frontend/src/Routes.tsx
frontend/src/components/ScrollToTop.tsx
frontend/src/components/TimelineBase.tsx
frontend/src/components/UserPage.tsx
frontend/src/components/timeline/DateSelectors.tsx
frontend/src/utils/scrollToTop.ts

closes https://github.com/tbotaq/jump-pm/issues/269

Scroll to top on every navigation.

---

frontend/src/components/SignInButton.tsx

closes https://github.com/tbotaq/jump-pm/issues/378

Respect twitter brand color

---

app/models/concerns/url_entity_presentable.rb
spec/models/medium_spec.rb
spec/models/url_spec.rb

closes https://github.com/tbotaq/jump-pm/issues/420

Camelize the keys of url entities to go with JS coding style.

---

.github/workflows/frontend.yml

closes https://github.com/tbotaq/jump-pm/issues/421

Tweak the frontend workflow

---

app/services/register_tweet_service.rb
spec/mocks/tweet_mock_spec.rb
spec/services/register_tweet_service_spec.rb
spec/support/tweet_mock.rb

closes https://github.com/tbotaq/jump-pm/issues/422

Apply secure url for Medium#direct_url

---

app/models/status.rb
spec/models/status_spec.rb

closes https://github.com/tbotaq/jump-pm/issues/427

Stop validating the maximum length of tweet text and retweeted tweet

---

frontend/src/components/Footer.tsx
frontend/src/components/PublicTimeline.tsx
frontend/src/components/ShareButton.tsx
frontend/src/components/TimelineBase.tsx
frontend/src/components/UserPage.tsx

closes https://github.com/tbotaq/jump-pm/issues/437

Clarify the role of the tweet button by changing its text.

---

.github/workflows/frontend.yml
frontend/e2e/cypress.json

closes https://github.com/tbotaq/jump-pm/issues/436

Add E2E workflow for GitHub Actions

---

frontend/src/components/TimelineBase.tsx
frontend/src/components/UserPage.tsx
frontend/src/containers/TimelineBaseContainer.ts
frontend/src/containers/UserPageContainer.ts

closes https://github.com/tbotaq/jump-pm/issues/447

Keep the date selector sticky on the bottom.

---

frontend/src/Routes.tsx

closes https://github.com/tbotaq/jump-pm/issues/449

Redirect unauthorized user when it visits user_timeline .

---

config/sidekiq.yml

closes https://github.com/tbotaq/jump-pm/issues/455

Reduce the amount of concurrency of sidekiq.

---

frontend/src/components/TimelineBase.tsx
frontend/src/pages/DataManagement.tsx
frontend/src/pages/Import.tsx
frontend/src/pages/TermsAndPrivacy.tsx
frontend/src/pages/UserPage.tsx

closes https://github.com/tbotaq/jump-pm/issues/466

Fix the position of ApiErrorBoundary

---

app/models/user.rb
spec/models/user_spec.rb

closes https://github.com/tbotaq/jump-pm/issues/467

Add User#twitter_client for development purpose.

---

config/initializers/omniauth.rb
frontend/src/components/SignInButton.tsx

closes https://github.com/tbotaq/jump-pm/issues/390

Handle with CVE 2015 9284

---

frontend/src/pages/PublicTimeline.tsx

closes https://github.com/tbotaq/jump-pm/issues/468

Fix desc tag text

---

app/models/user.rb
frontend/public/index.html
frontend/public/robots.txt
frontend/src/api/types/response/user.ts
frontend/src/components/NewArrivalList.tsx
frontend/src/components/TweetCard.tsx
frontend/src/components/UserProfile.tsx
frontend/src/components/head_nav/UserMenu.tsx
frontend/src/utils/avatarAltText.ts
spec/models/user_spec.rb
spec/requests/users/get_spec.rb

closes https://github.com/tbotaq/jump-pm/issues/471

Tweak for SEO

---

frontend/src/components/Footer.tsx
frontend/src/components/TweetCard.tsx
frontend/src/components/UserProfile.tsx
frontend/src/components/head_nav/UserMenu.tsx

closes https://github.com/tbotaq/jump-pm/issues/473

Issue#473/noopener

---

frontend/.eslintrc.json
frontend/src/utils/linkifyTweetText.ts

closes https://github.com/tbotaq/jump-pm/issues/474
closes https://github.com/tbotaq/jump-pm/issues/475
closes https://github.com/tbotaq/jump-pm/issues/476
closes https://github.com/tbotaq/jump-pm/issues/477
closes https://github.com/tbotaq/jump-pm/issues/478

Add rel="noopener" attr to all links on tweet body.

---

.circleci/config.yml

closes https://github.com/tbotaq/jump-pm/issues/479

Remove duplicating coverage upload.

---

deploy/config/deploy.rb

Update locked version of capistrano.

---

netlify.toml

Remove unused netlify.toml

---

config/environments/production.rb

Tweak the log level to :error

---

deploy/config/deploy.rb

Fix cap to ask me which branch to deploy

---

docker-compose.yml

Tweak the exposed port of Redis container so that it differs from the native's one.

---

docker-compose.yml

Upgrade the version of Redis used in development.

---

.github/workflows/frontend.yml

Update actions/checkout to v2

---

.github/workflows/frontend.yml

Update actions/cache to v2

---

.github/workflows/frontend.yml

Update actions/setup-node to v2

---

.circleci/config.yml

Update the version of Redis used in CI to 5.

---

docker-compose.yml

Upgrade the version of MySQL used for development to 8

---

frontend/src/components/NewArrivalList.tsx
frontend/src/components/StatsChip.tsx

Convert to FC

---

frontend/src/pages/DataManagement.tsx

Refactor DataManagement

---

frontend/src/components/TimelineBase.tsx
frontend/src/containers/HeadProgressBarContainer.ts
frontend/src/containers/TimelineBaseContainer.ts
frontend/src/containers/UserPageContainer.ts
frontend/src/pages/UserPage.tsx
frontend/src/store/tweet/actions.ts
frontend/src/store/tweet/reducers.ts
frontend/src/store/tweet/types.ts

Handle fetching state with local state instead of Redux store

---

frontend/.gitignore

Ignore .eslintcache

---

frontend/src/components/TweetList.tsx
frontend/src/containers/TweetListContainer.ts
frontend/src/store/tweet/actions.ts
frontend/src/store/tweet/reducers.ts
frontend/src/store/tweet/types.ts

Handle hasMore flag with local state instead of Redux store

---

frontend/src/store/tweet/reducers.ts
frontend/src/store/tweet/types.ts

Remove unused prop of store

---

frontend/src/components/TimelineBase.tsx
frontend/src/components/TweetList.tsx

Fix: Use existing constant

---

.github/auto-merge.yml
.github/workflows/auto-merge.yml

enable dependabot auto merge
